[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[build]
  publish = "."
